name: open3Dcompatible
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - annotated-types=0.6.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=23.1.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.11.1
  - azure-identity-cpp=1.6.0
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - blas=1.0=openblas
  - blosc=1.21.5
  - bottleneck=1.3.7
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.3.11
  - cachetools=5.3.3
  - cairo=1.18.0
  - ceres-solver=2.2.0
  - certifi=2024.2.2
  - cfitsio=4.4.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - comm=0.2.2
  - contourpy=1.2.0
  - curl=8.8.0
  - cycler=0.11.0
  - dask-core=2024.5.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - draco=1.5.7
  - eigen=3.4.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fiona=1.9.6
  - fmt=10.2.1
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - fsspec=2024.3.1
  - gdal=3.8.5
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geos=3.12.1
  - geotiff=1.7.3
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.24.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - jq=1.7.1
  - json-c=0.17
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kealib=1.5.3
  - kiwisolver=1.4.4
  - krb5=1.21.2
  - laspy=2.5.3
  - lazrs-python=0.6.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libblas=3.9.0=22_osx64_openblas
  - libboost-headers=1.85.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0=22_osx64_openblas
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.8.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0=22_osx64_openblas
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=18.1.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - metis=5.1.0
  - minizip=4.0.5
  - mpfr=4.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.1
  - numpy=1.25.0
  - numpydoc=1.4.0
  - openjpeg=2.5.0
  - openblas=0.3.27
  - openssl=3.1.3
  - packaging=23.1
  - pandas=2.1.2
  - pango=1.50.14
  - parso=0.8.3
  - partd=1.4.1
  - pathspec=0.11.1
  - pcre=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=23.1.2
  - pkg-config=0.29.2
  - platformdirs=4.0.0
  - pluggy=1.2.0
  - poppler=23.05.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - proj=9.3.1
  - prompt-toolkit=3.0.38
  - protobuf=4.25.3
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.8.1
  - pydantic=2.4.2
  - pyee=9.0.4
  - pygments=2.15.1
  - pyparsing=3.1.1
  - pyrsistent=0.19.3
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-jsonrpc-server=0.6.4
  - python-jsonschema=4.19.1
  - python-jsonschema-core=4.20.0
  - python-libarchive-c=4.0
  - pytz=2023.3
  - pyzmq=25.1.0
  - rapids=22.12
  - rasterio=1.3.8
  - readline=8.2
  - rioxarray=0.14.0
  - ruamel.yaml=0.17.31
  - ruamel.yaml.clib=0.2.7
  - scipy=1.11.0
  - setuptools=68.1.2
  - shapely=2.0.1
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.9.0
  - tiledb=2.19.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.1.1
  - toolz=0.12.0
  - tornado=6.3.2
  - traitlets=5.9.1
  - typing_extensions=4.7.1
  - tzcode=2023c
  - tzdata=2023c
  - urllib3=2.0.5
  - wcwidth=0.2.6
  - wheel=0.41.2
  - xerces-c=3.2.3
  - xz=5.4.4
  - yaml=0.2.5
  - zarr=2.14.0
  - zeromq=4.3.5
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
